### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by crack00r** [TheRoboKitten/ZenMacd#1]
```
[root@j314793:/ZenMacd# sudo python3 macdtrader.py
WARNING:__main__:BTC_BCH_300_chart collection is empty!
Traceback (most recent call last):
  File "macdtrader.py", line 237, in <module>
    run()
  File "macdtrader.py", line 174, in run
    df = Chart(api, word).dataFrame()
  File "macdtrader.py", line 141, in dataFrame
    data = self.__call__(size)
  File "macdtrader.py", line 118, in __call__
    start=time() - self.api.YEAR)
TypeError: 'module' object is not callable
root@j314793:/ZenMacd#
```

**Comment by TheRoboKitten** [comment]
The problem is time was imported twice, this is really strange, but other systems only allow for it to be imported once even though all python is the same.
